//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.parasoft.com/wsdl/store-01/", ConfigurationName="ICart")]
public interface ICart
{
    
    [System.ServiceModel.OperationContractAttribute(Action="placeOrder", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(string), Action="placeOrder", Name="exception", Namespace="http://www.themindelectric.com/exceptions/")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Item))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
    Order placeOrder(int itemId, int quantity);
    
    [System.ServiceModel.OperationContractAttribute(Action="placeOrder", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
    System.Threading.Tasks.Task<Order> placeOrderAsync(int itemId, int quantity);
    
    [System.ServiceModel.OperationContractAttribute(Action="removeOrder", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Item))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
    string removeOrder(int orderNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="removeOrder", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
    System.Threading.Tasks.Task<string> removeOrderAsync(int orderNumber);
    
    // CODEGEN: Parameter 'Result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="getItemByTitle", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(string), Action="getItemByTitle", Name="exception", Namespace="http://www.themindelectric.com/exceptions/")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Item))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
    getItemByTitle2Out getItemByTitle(getItemByTitle2In request);
    
    [System.ServiceModel.OperationContractAttribute(Action="getItemByTitle", ReplyAction="*")]
    System.Threading.Tasks.Task<getItemByTitle2Out> getItemByTitleAsync(getItemByTitle2In request);
    
    [System.ServiceModel.OperationContractAttribute(Action="getItemById", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(string), Action="getItemById", Name="exception", Namespace="http://www.themindelectric.com/exceptions/")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Item))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
    Book getItemById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="getItemById", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
    System.Threading.Tasks.Task<Book> getItemByIdAsync(int id);
    
    // CODEGEN: Parameter 'Result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="getPendingOrders", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Item))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
    getPendingOrders4Out getPendingOrders(getPendingOrders4In request);
    
    [System.ServiceModel.OperationContractAttribute(Action="getPendingOrders", ReplyAction="*")]
    System.Threading.Tasks.Task<getPendingOrders4Out> getPendingOrdersAsync(getPendingOrders4In request);
    
    [System.ServiceModel.OperationContractAttribute(Action="addNewItem", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Item))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
    Book addNewItem(Book book);
    
    [System.ServiceModel.OperationContractAttribute(Action="addNewItem", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
    System.Threading.Tasks.Task<Book> addNewItemAsync(Book book);
    
    [System.ServiceModel.OperationContractAttribute(Action="confirm", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Item))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
    bool confirm();
    
    [System.ServiceModel.OperationContractAttribute(Action="confirm", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
    System.Threading.Tasks.Task<bool> confirmAsync();
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.themindelectric.com/package/webtool.soap.examples.store/")]
public partial class Order
{
    
    private Book itemField;
    
    private int quantityField;
    
    private int order_numberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
    public Book item
    {
        get
        {
            return this.itemField;
        }
        set
        {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public int quantity
    {
        get
        {
            return this.quantityField;
        }
        set
        {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public int order_number
    {
        get
        {
            return this.order_numberField;
        }
        set
        {
            this.order_numberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.themindelectric.com/package/webtool.soap.examples.store/")]
public partial class Book : Item
{
    
    private string isbnField;
    
    private Date publication_dateField;
    
    private string descriptionField;
    
    private string[] authorsField;
    
    private string publisherField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
    public string isbn
    {
        get
        {
            return this.isbnField;
        }
        set
        {
            this.isbnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
    public Date publication_date
    {
        get
        {
            return this.publication_dateField;
        }
        set
        {
            this.publication_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
    [System.Xml.Serialization.XmlArrayItemAttribute("i", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public string[] authors
    {
        get
        {
            return this.authorsField;
        }
        set
        {
            this.authorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
    public string publisher
    {
        get
        {
            return this.publisherField;
        }
        set
        {
            this.publisherField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.themindelectric.com/package/java.sql/")]
public partial class Date
{
    
    private System.DateTime valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public System.DateTime Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Book))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.themindelectric.com/package/webtool.soap.examples.store/")]
public partial class Item
{
    
    private int idField;
    
    private string titleField;
    
    private int quantity_in_stockField;
    
    private float priceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public int id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
    public string title
    {
        get
        {
            return this.titleField;
        }
        set
        {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public int quantity_in_stock
    {
        get
        {
            return this.quantity_in_stockField;
        }
        set
        {
            this.quantity_in_stockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public float price
    {
        get
        {
            return this.priceField;
        }
        set
        {
            this.priceField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getItemByTitle", WrapperNamespace="http://www.parasoft.com/wsdl/store-01/", IsWrapped=true)]
public partial class getItemByTitle2In
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.parasoft.com/wsdl/store-01/", Order=0)]
    public string titleKeyword;
    
    public getItemByTitle2In()
    {
    }
    
    public getItemByTitle2In(string titleKeyword)
    {
        this.titleKeyword = titleKeyword;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getItemByTitleResponse", WrapperNamespace="http://www.parasoft.com/wsdl/store-01/", IsWrapped=true)]
public partial class getItemByTitle2Out
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.parasoft.com/wsdl/store-01/", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("i", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public Book[] Result;
    
    public getItemByTitle2Out()
    {
    }
    
    public getItemByTitle2Out(Book[] Result)
    {
        this.Result = Result;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getPendingOrders", WrapperNamespace="http://www.parasoft.com/wsdl/store-01/", IsWrapped=true)]
public partial class getPendingOrders4In
{
    
    public getPendingOrders4In()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getPendingOrdersResponse", WrapperNamespace="http://www.parasoft.com/wsdl/store-01/", IsWrapped=true)]
public partial class getPendingOrders4Out
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.parasoft.com/wsdl/store-01/", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("i", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public Order[] Result;
    
    public getPendingOrders4Out()
    {
    }
    
    public getPendingOrders4Out(Order[] Result)
    {
        this.Result = Result;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICartChannel : ICart, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CartClient : System.ServiceModel.ClientBase<ICart>, ICart
{
    
    public CartClient()
    {
    }
    
    public CartClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CartClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CartClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CartClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Order placeOrder(int itemId, int quantity)
    {
        return base.Channel.placeOrder(itemId, quantity);
    }
    
    public System.Threading.Tasks.Task<Order> placeOrderAsync(int itemId, int quantity)
    {
        return base.Channel.placeOrderAsync(itemId, quantity);
    }
    
    public string removeOrder(int orderNumber)
    {
        return base.Channel.removeOrder(orderNumber);
    }
    
    public System.Threading.Tasks.Task<string> removeOrderAsync(int orderNumber)
    {
        return base.Channel.removeOrderAsync(orderNumber);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getItemByTitle2Out ICart.getItemByTitle(getItemByTitle2In request)
    {
        return base.Channel.getItemByTitle(request);
    }
    
    public Book[] getItemByTitle(string titleKeyword)
    {
        getItemByTitle2In inValue = new getItemByTitle2In();
        inValue.titleKeyword = titleKeyword;
        getItemByTitle2Out retVal = ((ICart)(this)).getItemByTitle(inValue);
        return retVal.Result;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getItemByTitle2Out> ICart.getItemByTitleAsync(getItemByTitle2In request)
    {
        return base.Channel.getItemByTitleAsync(request);
    }
    
    public System.Threading.Tasks.Task<getItemByTitle2Out> getItemByTitleAsync(string titleKeyword)
    {
        getItemByTitle2In inValue = new getItemByTitle2In();
        inValue.titleKeyword = titleKeyword;
        return ((ICart)(this)).getItemByTitleAsync(inValue);
    }
    
    public Book getItemById(int id)
    {
        return base.Channel.getItemById(id);
    }
    
    public System.Threading.Tasks.Task<Book> getItemByIdAsync(int id)
    {
        return base.Channel.getItemByIdAsync(id);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getPendingOrders4Out ICart.getPendingOrders(getPendingOrders4In request)
    {
        return base.Channel.getPendingOrders(request);
    }
    
    public Order[] getPendingOrders()
    {
        getPendingOrders4In inValue = new getPendingOrders4In();
        getPendingOrders4Out retVal = ((ICart)(this)).getPendingOrders(inValue);
        return retVal.Result;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getPendingOrders4Out> ICart.getPendingOrdersAsync(getPendingOrders4In request)
    {
        return base.Channel.getPendingOrdersAsync(request);
    }
    
    public System.Threading.Tasks.Task<getPendingOrders4Out> getPendingOrdersAsync()
    {
        getPendingOrders4In inValue = new getPendingOrders4In();
        return ((ICart)(this)).getPendingOrdersAsync(inValue);
    }
    
    public Book addNewItem(Book book)
    {
        return base.Channel.addNewItem(book);
    }
    
    public System.Threading.Tasks.Task<Book> addNewItemAsync(Book book)
    {
        return base.Channel.addNewItemAsync(book);
    }
    
    public bool confirm()
    {
        return base.Channel.confirm();
    }
    
    public System.Threading.Tasks.Task<bool> confirmAsync()
    {
        return base.Channel.confirmAsync();
    }
}
